### ISSUE TITLE
README is out of date or auto deploy is not working

### ISSUE THREAD

**Issue by MCF** [go-gitea/docs#170]
Near the top of the docs README is this statement:

_This page is hosted on our infrastructure within Docker containers, it gets automatically updated on every push to the master branch._

But recent changes to master are not present on [docs.gitea.io](https://docs.gitea.io).  For example this recent change:

https://github.com/go-gitea/docs/commit/ca896252aa76e6ddad185160c8e500c0a8a854cf

is not present:

https://docs.gitea.io/en-us/authentication/

Perhaps the docs are now only synched when new Gitea releases go out?  If yes perhaps the README should be updated with this information?

**Comment by techknowlogick** [comment]
@MCF that's what I am trying to achieve with this issue: https://github.com/go-gitea/gitea/issues/2865 so that it'll be auto-deployed hopefully more often.

(I see that you already thumbs up the PR that I made so you already know this, but I'll still keep this comment for others who come to this issue)

**Comment by techknowlogick** [comment]
Looking into this more, it looks like the gitea/docs drone hasn't run in the last 4months: https://drone.gitea.io/go-gitea/docs

Now that docs have been merged into the main repo I have go-gitea/gitea#3004 which will hopefully push the docs docker container to the hub and then the auto-deploy will pick it up again.
