### ISSUE TITLE
Do not use Coudflare

### ISSUE THREAD

**Issue by rugk** [go-gitea/docs#69]
This issue is about the whole website, but I am opening it here.

* https://scotthelme.co.uk/cloudflares-great-new-features-and-why-i-wont-use-them/
* https://medium.com/@karthikb351/airtel-is-sniffing-and-censoring-cloudflares-traffic-in-india-and-they-don-t-even-know-it-90935f7f6d98#.6obceyzii

So from a security standpoint Cloudflare is really a bad idea. I'd really recommend you to use a proper TLS connection e.g. with Let's Encrypt.

**Comment by tboerger** [comment]
It's not an option to disable cloudflare. We got users from all over the world, that's why we are using the CDN of cloudflare. We already got LE on all our domains, and we have set cloudflare to Full SSL, but I think because of the CDN we are not able to use our own certs for all domains. The static pages like https://dl.gitea.io, https://docs.gitea.io, https://blog.gitea.io, https://code.gitea.io and https://gitea.io will stay on the cloudflare CDN. The rest like https://drone.gitea.io, https://lgtm.gitea.io, https://try.gitea.io and so on bypass the CDN and is routed directly to our server. The list of the used domains is directly visible at https://github.com/go-gitea/infrastructure/blob/master/terraform/domains.tf.

We are non-profit, so we won't get any CDN we have to pay for. I don't know what the others think, but for me this issue is a wontfix.

**Comment by rugk** [comment]
Okay, but in this case you should at least use "Full SSL (strict)" as otherwise MITM attacks are easy (Cloudflare does not verify the cert without the "strict" option.
Otherwise keyless ssl would be an option.

**Comment by tboerger** [comment]
Keyless SSL seems to be an enterprise feature, so we won't get that because we are on a free plan.

**Comment by rugk** [comment]
Then at least "Full SSL (Strict)". When you have LE certs for your domains, you should be able to activate it instantly.

**Comment by tboerger** [comment]
I have switched it to strict now.
